CREATE TABLE OCCUPANCY_STATUS (
	OCCUPANCY_STATUS_ID VARCHAR(3) PRIMARY KEY,
	OCCUPANCY_STATUS_DESCRIPTION VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PROPERTY_STATUS (
	STATUS_ID VARCHAR(3) PRIMARY KEY,
	PROPERTY_STATUS_DESCRIPTION VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USER_ROLE (
    ROLE_ID VARCHAR(4) PRIMARY KEY,
    USER_ROLE_DESCRIPTION VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CONTRACTOR_TYPE (
    CONTRACTOR_TYPE_ID VARCHAR(4) PRIMARY KEY,
    CONTRACTOR_TYPE_DESCRIPTION VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PROPERTY_AUCTION (
    AUCTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    AUCTION_LOCATION VARCHAR(50),
    DATE_OF_AUCTION DATE
);

CREATE TABLE PROPERTY_PRICES (
    PRICES_ID INT PRIMARY KEY AUTO_INCREMENT,
    BUY_VALUE DECIMAL(20, 2),
    EXPECTED_VALUE DECIMAL(20, 2),
    SELL_VALUE DECIMAL(20, 2),
    BIDDING_PRICE DECIMAL(20, 2),
    MARKET_PRICE DECIMAL(20, 2)
);

CREATE TABLE PROPERTY_LOAN (
    LOAN_ID INT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT DECIMAL(20, 2),
    MONTH INT,
    YEAR INT
);

CREATE TABLE PROPERTY_ADDRESS (
    ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT,
    ADDRESS VARCHAR(50) NOT NULL,
    CITY VARCHAR(50),
    COUNTY VARCHAR(50),
    ZIPCODE VARCHAR(5),
    STATE VARCHAR(2)
);

CREATE TABLE PROPERTY_ESSENTIALS (
    ESSENTIALS_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROPERTY_TYPE VARCHAR(50),
    NUM_BEDS INT,
    NUM_BATHS INT,
    LAND_FOOTAGE DECIMAL(20, 3),
    PROPERTY_FOOTAGE DECIMAL(20, 3),
    YEAR_BUILT INT,
    ZILLOW_LINK VARCHAR(200)
);

CREATE TABLE USERS (
    USER_COGNITO_ID VARCHAR(50) PRIMARY KEY,
    ROLE_ID VARCHAR(4) NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    SSN VARCHAR(11) UNIQUE,
    FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLE(ROLE_ID)
);

CREATE TABLE CONTRACTOR (
    CONTRACTOR_COGNITO_ID VARCHAR(50) PRIMARY KEY,
    CONTRACTOR_TYPE_ID VARCHAR(4) NOT NULL,
    DATE_HIRED DATE,
    START_DATE DATE,
    END_DATE DATE,
    COMPANY VARCHAR(50),
    FOREIGN KEY (CONTRACTOR_COGNITO_ID) REFERENCES USERS(USER_COGNITO_ID),
    FOREIGN KEY (CONTRACTOR_TYPE_ID) REFERENCES CONTRACTOR_TYPE(CONTRACTOR_TYPE_ID)
);

CREATE TABLE TAX (
    TAX_ID INT PRIMARY KEY AUTO_INCREMENT,
    GOVERNMENT_TAX_ID VARCHAR(50) NOT NULL,
    USER_COGNITO_ID VARCHAR(50) NOT NULL UNIQUE,
    FOREIGN KEY (USER_COGNITO_ID) REFERENCES USERS(USER_COGNITO_ID)
);

CREATE TABLE PROPERTY (
    PROPERTY_ID INT PRIMARY KEY AUTO_INCREMENT,
    STATUS_ID VARCHAR(3) NOT NULL,
    OCCUPANCY_STATUS_ID VARCHAR(3),
    COORDINATOR_COGNITO_ID VARCHAR(50),
    AUCTION_ID INT,
    PRICES_ID INT UNIQUE,
    ADDRESS_ID INT NOT NULL UNIQUE,
    ESSENTIALS_ID INT UNIQUE,
    LOAN_ID INT UNIQUE,
    DATE_OF_PURCHASE DATE,
    DATE_OF_SALE DATE,
    TRUSTEE_NAME VARCHAR(50),
    SUBDIVISION VARCHAR(50),
    COUNTY_ASSESSMENT INT,
    NOTES VARCHAR(200),
    FOREIGN KEY (STATUS_ID) REFERENCES PROPERTY_STATUS(STATUS_ID),
    FOREIGN KEY (AUCTION_ID) REFERENCES PROPERTY_AUCTION(AUCTION_ID),
    FOREIGN KEY (PRICES_ID) REFERENCES PROPERTY_PRICES(PRICES_ID),
    FOREIGN KEY (OCCUPANCY_STATUS_ID) REFERENCES OCCUPANCY_STATUS(OCCUPANCY_STATUS_ID),
    FOREIGN KEY (LOAN_ID) REFERENCES PROPERTY_LOAN(LOAN_ID),
    FOREIGN KEY (ESSENTIALS_ID) REFERENCES PROPERTY_ESSENTIALS(ESSENTIALS_ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES PROPERTY_ADDRESS(ADDRESS_ID),
    FOREIGN KEY (COORDINATOR_COGNITO_ID) REFERENCES USERS(USER_COGNITO_ID)
);

CREATE TABLE EXPENSE_STATUS (
    EXPENSE_STATUS_ID VARCHAR(3) PRIMARY KEY,
	EXPENSE_STATUS_DESCRIPTION VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE REVENUE (
	REVENUE_ID INT AUTO_INCREMENT PRIMARY KEY,
	PROPERTY_ID INT,
 	CONTRACTOR_COGNITO_ID VARCHAR(50),
    EXPENSE_STATUS_ID VARCHAR(3),
	REVENUE_AMOUNT DECIMAL(20, 2) NOT NULL,
	REVENUE_TYPE VARCHAR(7),
	EXPENSE_DUE_DATE DATE,
	AMOUNT_PAID DECIMAL(20, 2),
	REVENUE_DESCRIPTION VARCHAR(200),
	DATE_INCURRED DATE,
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
    FOREIGN KEY (CONTRACTOR_COGNITO_ID) REFERENCES CONTRACTOR(CONTRACTOR_COGNITO_ID),
    FOREIGN KEY (EXPENSE_STATUS_ID) REFERENCES EXPENSE_STATUS(EXPENSE_STATUS_ID)
);

CREATE TABLE PROPERTY_CONTRACTOR (
    CONTRACTOR_COGNITO_ID VARCHAR(50) PRIMARY KEY,
    PROPERTY_ID INT,
    FOREIGN KEY (CONTRACTOR_COGNITO_ID) REFERENCES CONTRACTOR(CONTRACTOR_COGNITO_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);